<?php
// Perfiles de zona para páginas servicio × lugar. Montevideo (barrios) y Canelones (localidades).
// Cada entrada: nombre, en (forma con artículo, opcional), depto, tipo (antiguo|torres|casas|balneario|periferia), vecinos, desc.
$barrios_perfil = [
    // ---------- MONTEVIDEO ----------
    'ciudad-vieja' => ['nombre'=>'Ciudad Vieja', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['centro','barrio-sur','aguada'], 'desc'=>'Ciudad Vieja tiene edificios históricos, apartamentos reciclados, oficinas, hoteles y locales gastronómicos. Las instalaciones eléctricas suelen ser las más antiguas de la ciudad, con paredes gruesas, canalizaciones a la vista o embutidas en mampostería y tableros que necesitan renovarse para soportar el uso actual.'],
    'centro' => ['nombre'=>'Centro', 'en'=>'el Centro', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['cordon','ciudad-vieja','barrio-sur','aguada'], 'desc'=>'El Centro concentra edificios de oficinas, apartamentos antiguos de techos altos, locales comerciales y pensiones. Las instalaciones suelen tener muchos años, canalizaciones embutidas de difícil acceso, tableros con fusibles y ampliaciones sucesivas hechas por distintas manos.'],
    'barrio-sur' => ['nombre'=>'Barrio Sur', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['centro','palermo','ciudad-vieja'], 'desc'=>'Barrio Sur combina casas de época, conventillos reciclados, edificios frente a la rambla y apartamentos de mediana altura. Es común encontrar instalaciones antiguas compartidas entre varias unidades, medidores agrupados y tableros que nunca fueron renovados.'],
    'palermo' => ['nombre'=>'Palermo', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['barrio-sur','parque-rodo','cordon'], 'desc'=>'Palermo tiene casas antiguas de una y dos plantas, apartamentos reciclados y edificios nuevos sobre la rambla. Las reformas para alquiler dejaron instalaciones parciales: cocinas y baños nuevos conectados a cableado y tableros viejos.'],
    'cordon' => ['nombre'=>'Cordón', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['centro','parque-rodo','tres-cruces','pocitos','palermo'], 'desc'=>'Cordón es un barrio de casas de época, apartamentos reciclados, locales gastronómicos y comercios sobre 18 de Julio y las calles cercanas. Es común encontrar instalaciones antiguas con cables de tela o sin puesta a tierra, reformas parciales y locales que fueron cambiando de rubro sin adaptar la instalación.'],
    'parque-rodo' => ['nombre'=>'Parque Rodó', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['cordon','punta-carretas','palermo'], 'desc'=>'Parque Rodó combina casas antiguas, apartamentos reciclados, edificios de mediana altura y una fuerte presencia de locales y estudios. Las reformas para alquiler y los cambios de uso dejan instalaciones con circuitos poco claros, tableros sin identificar y puntos agregados sin planificación.'],
    'punta-carretas' => ['nombre'=>'Punta Carretas', 'depto'=>'Montevideo', 'tipo'=>'torres', 'vecinos'=>['pocitos','parque-rodo'], 'desc'=>'Punta Carretas mezcla edificios de categoría, torres frente a la rambla y casas antiguas reformadas. Es habitual encontrar apartamentos con instalaciones originales de los años 60 y 70 conviviendo con cocinas y baños renovados, y casas con ampliaciones que fueron sumando puntos sin replantear el tablero.'],
    'pocitos' => ['nombre'=>'Pocitos', 'depto'=>'Montevideo', 'tipo'=>'torres', 'vecinos'=>['punta-carretas','buceo','cordon','villa-dolores'], 'desc'=>'Pocitos combina torres de apartamentos de varias décadas, edificios nuevos y algunas casas de una o dos plantas sobre las calles interiores. Muchos apartamentos fueron reformados más de una vez y arrastran instalaciones parcheadas, tableros que no acompañaron el aumento de consumo y circuitos compartidos entre cocina, aire acondicionado y termotanque.'],
    'buceo' => ['nombre'=>'Buceo', 'depto'=>'Montevideo', 'tipo'=>'torres', 'vecinos'=>['pocitos','malvin','parque-batlle'], 'desc'=>'Buceo creció con torres y edificios nuevos alrededor del puerto deportivo y conserva casas y edificios más antiguos hacia el interior. Conviven instalaciones modernas con circuitos bien separados e instalaciones viejas donde una sola llave protege toda la vivienda.'],
    'parque-batlle' => ['nombre'=>'Parque Batlle', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['buceo','tres-cruces','la-blanqueada','villa-dolores'], 'desc'=>'Parque Batlle tiene casas de una y dos plantas alrededor del parque, edificios de mediana altura sobre las avenidas y consultorios cerca del Hospital de Clínicas. Las viviendas suelen tener instalaciones de varias décadas con ampliaciones hacia el fondo y tableros sin disyuntor.'],
    'villa-dolores' => ['nombre'=>'Villa Dolores', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['pocitos','parque-batlle','buceo'], 'desc'=>'Villa Dolores es una zona de casas y edificios bajos entre Pocitos y Parque Batlle, con viviendas familiares de larga data. Muchas conservan instalaciones originales que necesitan protecciones nuevas y circuitos separados para los equipos actuales.'],
    'malvin' => ['nombre'=>'Malvín', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['buceo','punta-gorda','malvin-norte'], 'desc'=>'Malvín tiene casas de una y dos plantas, PH y edificios bajos cerca de la rambla. Muchas viviendas fueron ampliadas hacia el fondo o hacia arriba y las instalaciones crecieron con empalmes y circuitos que cuelgan de la instalación original, sin protecciones propias.'],
    'malvin-norte' => ['nombre'=>'Malvín Norte', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['malvin','carrasco-norte','maronas'], 'desc'=>'Malvín Norte mezcla complejos de vivienda, casas familiares, cooperativas y locales de barrio. Las consultas más comunes son por instalaciones que quedaron chicas, tableros compartidos y ampliaciones que necesitan circuitos propios.'],
    'punta-gorda' => ['nombre'=>'Punta Gorda', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['malvin','carrasco'], 'desc'=>'Punta Gorda es un barrio residencial de casas con jardín y edificios bajos sobre la rambla. Las viviendas son amplias, con iluminación exterior, portones automáticos, bombas y varios aires acondicionados que exigen tableros bien dimensionados.'],
    'carrasco' => ['nombre'=>'Carrasco', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['punta-gorda','carrasco-norte','paso-carrasco'], 'desc'=>'Carrasco es un barrio de casas con jardín, fondos amplios y construcciones de distintas épocas, además de edificios bajos sobre las avenidas. Las instalaciones suelen ser extensas: iluminación exterior, portones, bombas, piscinas, dependencias y varios equipos de aire acondicionado alimentados desde un mismo tablero.'],
    'carrasco-norte' => ['nombre'=>'Carrasco Norte', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['carrasco','malvin-norte','banados-de-carrasco'], 'desc'=>'Carrasco Norte tiene barrios jardín, casas nuevas, complejos de vivienda y zonas comerciales sobre Avenida Italia y Bolivia. Conviven instalaciones modernas con construcciones que crecieron por etapas y necesitan ordenar circuitos y protecciones.'],
    'banados-de-carrasco' => ['nombre'=>'Bañados de Carrasco', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['carrasco-norte','punta-de-rieles'], 'desc'=>'Bañados de Carrasco combina viviendas familiares, cooperativas, galpones y emprendimientos sobre Camino Carrasco. Son frecuentes las instalaciones para depósitos y talleres, bombas de agua y tramos exteriores expuestos a la humedad.'],
    'maronas' => ['nombre'=>'Maroñas', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['malvin-norte','flor-de-maronas','union'], 'desc'=>'Maroñas es un barrio de casas familiares, PH y comercios alrededor del hipódromo y Camino Maldonado. Muchas viviendas tienen instalaciones de décadas con empalmes en el fondo, tableros sin disyuntor y ampliaciones sin circuitos propios.'],
    'flor-de-maronas' => ['nombre'=>'Flor de Maroñas', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['maronas','punta-de-rieles','jardines-del-hipodromo'], 'desc'=>'Flor de Maroñas tiene casas de una planta con fondo, talleres y comercios de barrio. Las consultas habituales son por reparaciones en instalaciones antiguas, tableros con fusibles y la necesidad de sumar tomacorrientes y circuitos.'],
    'jardines-del-hipodromo' => ['nombre'=>'Jardines del Hipódromo', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['flor-de-maronas','ituzaingo','maronas'], 'desc'=>'Jardines del Hipódromo es un barrio de casas familiares con jardín y fondo, con calles tranquilas y comercios de cercanía. Las instalaciones suelen incluir dependencias, galpones y tramos exteriores que conviene proteger y ordenar.'],
    'ituzaingo' => ['nombre'=>'Ituzaingó', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['jardines-del-hipodromo','punta-de-rieles','villa-espanola'], 'desc'=>'Ituzaingó combina casas, PH y pequeñas fábricas y depósitos. Las viviendas que crecieron por etapas suelen tener circuitos sobrecargados, y los comercios y talleres necesitan instalaciones dimensionadas para maquinaria.'],
    'punta-de-rieles' => ['nombre'=>'Punta de Rieles', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['bella-italia','flor-de-maronas','banados-de-carrasco'], 'desc'=>'Punta de Rieles tiene viviendas familiares, cooperativas, complejos habitacionales y zonas de galpones sobre Camino Maldonado. Es habitual trabajar instalaciones nuevas para viviendas en construcción y ordenar instalaciones que crecieron sin planificación.'],
    'bella-italia' => ['nombre'=>'Bella Italia', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['punta-de-rieles','villa-garcia','las-canteras'], 'desc'=>'Bella Italia es un barrio de casas con terreno, quintas chicas y viviendas familiares en crecimiento. Las consultas típicas son instalaciones nuevas, ampliaciones, bombas de agua, portones y tableros para casas que se van completando por etapas.'],
    'las-canteras' => ['nombre'=>'Las Canteras', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['bella-italia','parque-guarani'], 'desc'=>'Las Canteras tiene casas familiares, cooperativas y emprendimientos de barrio. Muchas instalaciones fueron hechas por etapas y necesitan tablero nuevo, puesta a tierra y circuitos separados para los equipos actuales.'],
    'parque-guarani' => ['nombre'=>'Parque Guaraní', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['las-canteras','maronas'], 'desc'=>'Parque Guaraní es una zona de casas con fondo, PH y comercios de cercanía. Las reparaciones más frecuentes tienen que ver con instalaciones antiguas, empalmes exteriores y tableros sin protecciones adecuadas.'],
    'villa-garcia' => ['nombre'=>'Villa García', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['bella-italia','manga'], 'desc'=>'Villa García combina casas con terreno, quintas y viviendas familiares sobre Ruta 8. Las instalaciones suelen tener tramos aéreos, bombas, galpones y ampliaciones que conviene revisar y proteger correctamente.'],
    'union' => ['nombre'=>'Unión', 'en'=>'la Unión', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['cordon','villa-espanola','mercado-modelo','maronas'], 'desc'=>'Unión tiene casas antiguas, PH, apartamentos y una zona comercial muy activa sobre 8 de Octubre. Es frecuente encontrar instalaciones de muchos años, medidores compartidos en PH, locales con instalaciones improvisadas y viviendas que fueron subdivididas sin separar circuitos.'],
    'villa-espanola' => ['nombre'=>'Villa Española', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['union','ituzaingo','cerrito'], 'desc'=>'Villa Española es un barrio de casas familiares, PH y talleres, con comercios sobre las avenidas principales. Las instalaciones suelen ser antiguas, con ampliaciones hechas por etapas y tableros que no acompañaron el consumo actual.'],
    'mercado-modelo' => ['nombre'=>'Mercado Modelo', 'en'=>'Mercado Modelo', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['union','bolivar','la-blanqueada'], 'desc'=>'La zona de Mercado Modelo combina viviendas, depósitos, galpones y comercios que quedaron tras el traslado del mercado. Es habitual adaptar instalaciones de uso comercial e industrial a nuevos usos y ordenar tableros de gran tamaño.'],
    'bolivar' => ['nombre'=>'Bolívar', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['mercado-modelo','cerrito','castro'], 'desc'=>'Bolívar tiene casas familiares, PH y comercios de barrio en calles tranquilas. Las consultas más comunes son por reparaciones en instalaciones viejas, cambio de tableros y nuevos puntos para cocinas y aires acondicionados.'],
    'castro' => ['nombre'=>'Castro', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['bolivar','cerrito','las-acacias'], 'desc'=>'Castro y Pérez Castellanos son barrios de casas de una planta con fondo, PH y pequeños comercios. Es frecuente encontrar instalaciones antiguas con empalmes exteriores y tableros con fusibles que conviene renovar.'],
    'cerrito' => ['nombre'=>'Cerrito', 'en'=>'el Cerrito', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['villa-espanola','bolivar','las-acacias','casavalle'], 'desc'=>'Cerrito de la Victoria tiene casas familiares, PH, comercios de barrio y viviendas en pendiente sobre las calles que suben al cerrito. Las instalaciones suelen ser de varias décadas y muchas necesitan puesta a tierra y disyuntor.'],
    'las-acacias' => ['nombre'=>'Las Acacias', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['cerrito','castro','aires-puros'], 'desc'=>'Las Acacias es un barrio de casas de una y dos plantas, PH y comercios de cercanía. Las reparaciones más habituales tienen que ver con instalaciones envejecidas, circuitos sobrecargados y tableros sin protecciones.'],
    'aires-puros' => ['nombre'=>'Aires Puros', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['las-acacias','casavalle','brazo-oriental'], 'desc'=>'Aires Puros combina casas familiares, PH, cooperativas y comercios de barrio. Es común trabajar tableros que quedaron chicos, instalaciones para ampliaciones y puntos nuevos en cocinas y dormitorios.'],
    'casavalle' => ['nombre'=>'Casavalle', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['aires-puros','cerrito','piedras-blancas'], 'desc'=>'Casavalle tiene complejos habitacionales, cooperativas, casas familiares y comercios de barrio. Las consultas frecuentes son instalaciones nuevas y ampliaciones, tableros con protecciones y reparaciones de circuitos sobrecargados.'],
    'piedras-blancas' => ['nombre'=>'Piedras Blancas', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['casavalle','manga','ituzaingo'], 'desc'=>'Piedras Blancas es un barrio de casas con fondo, talleres y comercios sobre las avenidas principales. Las instalaciones suelen incluir galpones, dependencias y tramos exteriores que conviene proteger, además de tableros antiguos por renovar.'],
    'manga' => ['nombre'=>'Manga', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['piedras-blancas','villa-garcia','toledo-chico'], 'desc'=>'Manga combina casas con terreno, quintas, emprendimientos rurales y viviendas familiares. Es habitual trabajar instalaciones extensas con bombas, portones, galpones y tramos aéreos, y casas en construcción que necesitan instalación completa.'],
    'toledo-chico' => ['nombre'=>'Toledo Chico', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['manga','penarol'], 'desc'=>'Toledo Chico es una zona de casas con terreno, chacras y viviendas en crecimiento en el límite norte de Montevideo. Las instalaciones suelen ser extensas, con bombas de agua, galpones y tramos exteriores que requieren protecciones adecuadas.'],
    'penarol' => ['nombre'=>'Peñarol', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['toledo-chico','sayago','lavalleja','colon'], 'desc'=>'Peñarol tiene casas familiares, viviendas históricas del barrio obrero, talleres y comercios sobre Camino Casavalle y Avenida Sayago. Muchas instalaciones son antiguas y conviven con ampliaciones que necesitan circuitos y tableros nuevos.'],
    'lavalleja' => ['nombre'=>'Lavalleja', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['penarol','sayago','colon'], 'desc'=>'Lavalleja es un barrio de casas con fondo, cooperativas y pequeños comercios entre Sayago y Colón. Las reparaciones más frecuentes tienen que ver con instalaciones envejecidas, empalmes exteriores y tableros sin disyuntor.'],
    'sayago' => ['nombre'=>'Sayago', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['prado','penarol','conciliacion','belvedere'], 'desc'=>'Sayago es un barrio de casas con terreno, fondos grandes y construcciones de distintas épocas, con algunos talleres y comercios de barrio. Las instalaciones suelen incluir dependencias, galpones, portones, bombas e iluminación exterior, muchas veces alimentados con cables que no fueron pensados para ese uso.'],
    'conciliacion' => ['nombre'=>'Conciliación', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['sayago','belvedere','nuevo-paris'], 'desc'=>'Conciliación tiene casas familiares, PH y comercios de cercanía en calles tranquilas. Es común encontrar instalaciones de décadas con ampliaciones hacia el fondo y tableros que necesitan protecciones nuevas.'],
    'belvedere' => ['nombre'=>'Belvedere', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['sayago','conciliacion','nuevo-paris','la-teja'], 'desc'=>'Belvedere combina casas de una y dos plantas, PH, talleres y comercios sobre Carlos María Ramírez. Las consultas habituales son reparaciones en instalaciones antiguas, cambio de tableros y circuitos nuevos para equipos de consumo alto.'],
    'nuevo-paris' => ['nombre'=>'Nuevo París', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['belvedere','conciliacion','paso-de-la-arena'], 'desc'=>'Nuevo París es un barrio de casas con fondo, cooperativas, galpones y pequeñas industrias. Es frecuente trabajar instalaciones para talleres y depósitos, además de viviendas que necesitan tablero nuevo y puesta a tierra.'],
    'la-teja' => ['nombre'=>'La Teja', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['belvedere','cerro','prado','capurro'], 'desc'=>'La Teja tiene casas antiguas, PH, viviendas obreras y comercios de barrio muy activos. Las instalaciones suelen ser de muchos años, con medidores compartidos, tableros con fusibles y ampliaciones que conviene ordenar.'],
    'cerro' => ['nombre'=>'Cerro', 'en'=>'el Cerro', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['la-teja','casabo','paso-de-la-arena'], 'desc'=>'El Cerro combina casas familiares en pendiente, viviendas históricas, cooperativas y comercios sobre Grecia y Carlos María Ramírez. Las instalaciones antiguas y la cercanía del mar hacen frecuentes las reparaciones por humedad, empalmes deteriorados y tableros sin protecciones.'],
    'casabo' => ['nombre'=>'Casabó', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['cerro','pajas-blancas'], 'desc'=>'Casabó tiene casas familiares con fondo, cooperativas y viviendas en crecimiento en la zona oeste. Las consultas más comunes son instalaciones nuevas, ampliaciones, tableros con disyuntor y reparaciones de circuitos sobrecargados.'],
    'pajas-blancas' => ['nombre'=>'Pajas Blancas', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['casabo','santiago-vazquez'], 'desc'=>'Pajas Blancas es una zona de casas con terreno, quintas y viviendas cerca de la costa oeste. Las instalaciones suelen incluir bombas, portones, galpones y tramos exteriores expuestos a la humedad y la salinidad.'],
    'santiago-vazquez' => ['nombre'=>'Santiago Vázquez', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['pajas-blancas','paso-de-la-arena'], 'desc'=>'Santiago Vázquez es un pueblo de casas bajas junto al río Santa Lucía, con viviendas de fin de semana, clubes y comercios chicos. Es habitual trabajar instalaciones exteriores, muelles, bombas y tableros para casas que se usan por temporada.'],
    'paso-de-la-arena' => ['nombre'=>'Paso de la Arena', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['nuevo-paris','cerro','santiago-vazquez','colon'], 'desc'=>'Paso de la Arena combina casas con terreno, quintas, viviendas familiares y comercios sobre Camino Cibils y Luis Batlle Berres. Las instalaciones suelen ser extensas, con bombas, galpones y ampliaciones que necesitan tableros y circuitos propios.'],
    'colon' => ['nombre'=>'Colón', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['lezica','penarol','lavalleja','paso-de-la-arena','melilla'], 'desc'=>'Colón es un barrio de casas con jardín, casonas de veraneo reconvertidas, edificios bajos y una zona comercial activa sobre Garzón. Las instalaciones suelen ser antiguas y extensas, con dependencias, portones e iluminación exterior.'],
    'lezica' => ['nombre'=>'Lezica', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['colon','melilla'], 'desc'=>'Lezica tiene casas con terreno, quintas y viviendas familiares en una zona tranquila del noroeste. Las consultas habituales son instalaciones para ampliaciones, bombas, portones y tableros nuevos para casas que crecieron por etapas.'],
    'melilla' => ['nombre'=>'Melilla', 'depto'=>'Montevideo', 'tipo'=>'periferia', 'vecinos'=>['lezica','colon'], 'desc'=>'Melilla es una zona rural y de quintas con casas dispersas, emprendimientos productivos y viviendas familiares. Es habitual trabajar instalaciones extensas, tramos aéreos, bombas de riego y tableros para galpones.'],
    'prado' => ['nombre'=>'Prado', 'en'=>'el Prado', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['sayago','capurro','atahualpa','la-teja'], 'desc'=>'El Prado es un barrio de casonas, casas con jardín y construcciones de principios del siglo XX, con edificios bajos sobre las avenidas. Las viviendas son amplias, con instalaciones largas y antiguas, dependencias en el fondo, iluminación exterior y muchas veces tableros que nunca fueron renovados.'],
    'capurro' => ['nombre'=>'Capurro', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['prado','bella-vista','la-teja'], 'desc'=>'Capurro y Bella Vista tienen casas antiguas, PH, edificios bajos y comercios sobre Agraciada. Las instalaciones suelen ser de muchos años, con canalizaciones embutidas de difícil acceso y tableros que conviene renovar.'],
    'bella-vista' => ['nombre'=>'Bella Vista', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['capurro','aguada','reducto'], 'desc'=>'Bella Vista combina casas de época, apartamentos reciclados y comercios de barrio. Es común encontrar instalaciones originales sin puesta a tierra, reformas parciales y tableros con fusibles.'],
    'aguada' => ['nombre'=>'Aguada', 'en'=>'la Aguada', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['centro','bella-vista','reducto','ciudad-vieja'], 'desc'=>'La Aguada tiene edificios antiguos, oficinas, apartamentos reciclados y locales sobre Avenida Libertador y Rondeau. Las instalaciones suelen ser antiguas y de gran tamaño, con tableros generales que necesitan revisión y locales que cambian de uso.'],
    'reducto' => ['nombre'=>'Reducto', 'en'=>'el Reducto', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['aguada','bella-vista','atahualpa','goes'], 'desc'=>'Reducto es un barrio de casas antiguas, PH y edificios bajos con comercios de cercanía. Las reparaciones más frecuentes tienen que ver con instalaciones envejecidas, empalmes ocultos y tableros sin disyuntor.'],
    'atahualpa' => ['nombre'=>'Atahualpa', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['prado','reducto','jacinto-vera','brazo-oriental'], 'desc'=>'Atahualpa tiene casas con jardín, casonas y edificios bajos cerca del Prado. Las viviendas son amplias, con instalaciones antiguas, dependencias e iluminación exterior que suelen necesitar tableros nuevos y circuitos separados.'],
    'jacinto-vera' => ['nombre'=>'Jacinto Vera', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['atahualpa','figurita','la-comercial','brazo-oriental'], 'desc'=>'Jacinto Vera es un barrio de casas de una y dos plantas, PH y comercios de barrio. Es habitual encontrar instalaciones de décadas con ampliaciones hacia el fondo, medidores compartidos y tableros con fusibles.'],
    'figurita' => ['nombre'=>'Figurita', 'en'=>'la Figurita', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['jacinto-vera','larranaga','la-comercial'], 'desc'=>'La Figurita combina casas antiguas, PH y edificios bajos cerca de Garibaldi y Domingo Aramburú. Las consultas frecuentes son reparaciones en instalaciones viejas, cambio de tableros y nuevos puntos para cocinas y aires.'],
    'larranaga' => ['nombre'=>'Larrañaga', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['figurita','la-blanqueada','brazo-oriental'], 'desc'=>'Larrañaga tiene casas de época, PH, edificios de mediana altura y comercios sobre Garibaldi y Larrañaga. Muchas instalaciones son antiguas y conviven con reformas parciales que dejaron circuitos poco claros.'],
    'la-blanqueada' => ['nombre'=>'La Blanqueada', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['larranaga','tres-cruces','parque-batlle','mercado-modelo'], 'desc'=>'La Blanqueada combina casas de una y dos plantas, edificios sobre 8 de Octubre y locales comerciales. Las viviendas suelen tener instalaciones de varias décadas con ampliaciones y tableros que no acompañaron el consumo actual.'],
    'tres-cruces' => ['nombre'=>'Tres Cruces', 'depto'=>'Montevideo', 'tipo'=>'torres', 'vecinos'=>['cordon','la-blanqueada','parque-batlle','la-comercial'], 'desc'=>'Tres Cruces tiene torres y edificios de mediana altura alrededor de la terminal, casas antiguas en las calles interiores y muchos locales, oficinas y consultorios. Las instalaciones comerciales que cambian de uso y los apartamentos reformados son las consultas más comunes.'],
    'la-comercial' => ['nombre'=>'La Comercial', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['tres-cruces','jacinto-vera','villa-munoz','figurita'], 'desc'=>'La Comercial es un barrio de casas antiguas, PH y comercios sobre Justicia y Domingo Aramburú. Es frecuente encontrar instalaciones con cables de tela, sin puesta a tierra y con tableros con fusibles que conviene renovar.'],
    'villa-munoz' => ['nombre'=>'Villa Muñoz', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['la-comercial','goes','cordon'], 'desc'=>'Villa Muñoz tiene casas de época, PH, depósitos y una zona comercial muy activa alrededor de la feria de Tristán Narvaja y el Mercado Agrícola. Los locales y depósitos con instalaciones improvisadas y las viviendas subdivididas son las consultas más habituales.'],
    'goes' => ['nombre'=>'Goes', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['villa-munoz','reducto','brazo-oriental','aguada'], 'desc'=>'Goes combina casas antiguas, PH, apartamentos y comercios alrededor del Mercado Agrícola y General Flores. Las instalaciones suelen ser de muchos años, con medidores compartidos y tableros que necesitan protecciones nuevas.'],
    'brazo-oriental' => ['nombre'=>'Brazo Oriental', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['goes','atahualpa','jacinto-vera','aires-puros','larranaga'], 'desc'=>'Brazo Oriental es un barrio de casas de una y dos plantas con jardín, PH y comercios de cercanía. Las viviendas suelen tener instalaciones de décadas, ampliaciones hacia el fondo y tableros sin disyuntor.'],

    // ---------- CANELONES ----------
    'paso-carrasco' => ['nombre'=>'Paso Carrasco', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['carrasco','barra-de-carrasco','colonia-nicolich'], 'desc'=>'Paso Carrasco combina casas con jardín, complejos de vivienda, comercios y depósitos sobre Avenida a la Playa y Camino Carrasco. Las instalaciones suelen incluir tramos exteriores, portones y ampliaciones que necesitan circuitos propios.'],
    'barra-de-carrasco' => ['nombre'=>'Barra de Carrasco', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['paso-carrasco','san-jose-de-carrasco','shangrila'], 'desc'=>'Barra de Carrasco es una zona residencial de casas con jardín y barrios privados junto al arroyo. Las viviendas son amplias, con iluminación exterior, portones automáticos, piscinas y varios aires acondicionados que exigen tableros bien dimensionados.'],
    'colonia-nicolich' => ['nombre'=>'Colonia Nicolich', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['paso-carrasco','san-jose-de-carrasco','empalme-olmos'], 'desc'=>'Colonia Nicolich tiene casas con terreno, viviendas en construcción, cooperativas y depósitos cerca del aeropuerto. Es habitual trabajar instalaciones completas para casas nuevas, bombas de agua y tableros para galpones.'],
    'san-jose-de-carrasco' => ['nombre'=>'San José de Carrasco', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['barra-de-carrasco','shangrila','colonia-nicolich'], 'desc'=>'San José de Carrasco es un barrio residencial de casas con jardín y calles arboladas en Ciudad de la Costa. Las consultas frecuentes son instalaciones exteriores, portones, ampliaciones y tableros para viviendas que sumaron equipos.'],
    'shangrila' => ['nombre'=>'Shangrilá', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['san-jose-de-carrasco','lagomar','barra-de-carrasco'], 'desc'=>'Shangrilá tiene casas con jardín, chalets de distintas épocas y comercios sobre Avenida Giannattasio. Muchas viviendas fueron casas de veraneo y conservan instalaciones antiguas que necesitan renovarse para el uso permanente.'],
    'lagomar' => ['nombre'=>'Lagomar', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['shangrila','solymar'], 'desc'=>'Lagomar combina casas con jardín, chalets reformados y edificios bajos cerca de la playa. Es común encontrar instalaciones de veraneo adaptadas a vivienda permanente con tableros chicos y circuitos sobrecargados.'],
    'solymar' => ['nombre'=>'Solymar', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['lagomar','lomas-de-solymar','el-pinar','colinas-de-solymar'], 'desc'=>'Solymar es una de las zonas más pobladas de Ciudad de la Costa, con casas con jardín, viviendas nuevas y comercios sobre Giannattasio. Las consultas habituales son instalaciones completas, ampliaciones, bombas y tableros con disyuntor.'],
    'colinas-de-solymar' => ['nombre'=>'Colinas de Solymar', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['solymar','lomas-de-solymar'], 'desc'=>'Colinas de Solymar tiene casas con terreno amplio, viviendas en construcción y calles en crecimiento al norte de Ruta Interbalnearia. Es frecuente trabajar instalaciones nuevas, tramos aéreos, bombas y portones.'],
    'lomas-de-solymar' => ['nombre'=>'Lomas de Solymar', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['solymar','el-pinar','colinas-de-solymar'], 'desc'=>'Lomas de Solymar combina casas con jardín, viviendas familiares nuevas y comercios de barrio. Las instalaciones suelen crecer con la casa y necesitan tableros ampliados, circuitos para aire acondicionado e iluminación exterior.'],
    'el-pinar' => ['nombre'=>'El Pinar', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>['solymar','lomas-de-solymar','neptunia','pinamar'], 'desc'=>'El Pinar tiene casas con jardín entre pinos, chalets de veraneo reconvertidos y viviendas nuevas. Las consultas frecuentes son instalaciones exteriores, reparaciones por humedad, tableros antiguos y circuitos para equipos actuales.'],
    'neptunia' => ['nombre'=>'Neptunia', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['el-pinar','pinamar','salinas'], 'desc'=>'Neptunia es un balneario de casas entre pinos, con viviendas permanentes y de fin de semana. Es habitual trabajar instalaciones antiguas de veraneo, bombas de agua, tramos exteriores y tableros que necesitan protecciones nuevas.'],
    'pinamar' => ['nombre'=>'Pinamar', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['neptunia','salinas','el-pinar'], 'desc'=>'Pinamar combina casas de veraneo, viviendas permanentes y calles de arena cerca de la playa. Las instalaciones suelen tener tramos aéreos y exteriores expuestos a la salinidad, y tableros chicos que conviene renovar.'],
    'salinas' => ['nombre'=>'Salinas', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['pinamar','marindia','neptunia'], 'desc'=>'Salinas es un balneario con población permanente, casas con jardín, comercios sobre la Interbalnearia y viviendas de fin de semana. Las consultas más comunes son reparaciones en instalaciones de veraneo, bombas, portones y tableros con disyuntor.'],
    'marindia' => ['nombre'=>'Marindia', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['salinas','fortin-de-santa-rosa'], 'desc'=>'Marindia tiene casas entre pinos, viviendas de veraneo y familias que se instalaron de forma permanente. Es frecuente adaptar instalaciones antiguas al uso diario, sumar circuitos y renovar tableros.'],
    'fortin-de-santa-rosa' => ['nombre'=>'Fortín de Santa Rosa', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['marindia','villa-argentina','atlantida'], 'desc'=>'Fortín de Santa Rosa es un balneario de casas con jardín y calles tranquilas junto a la playa. Las instalaciones suelen ser de veraneo, con tramos exteriores y tableros que necesitan protecciones para el uso permanente.'],
    'villa-argentina' => ['nombre'=>'Villa Argentina', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['fortin-de-santa-rosa','atlantida'], 'desc'=>'Villa Argentina combina casas de veraneo, chalets antiguos y viviendas permanentes entre pinos. Las consultas habituales son reparaciones por humedad y salinidad, bombas y renovación de tableros antiguos.'],
    'atlantida' => ['nombre'=>'Atlántida', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['villa-argentina','estacion-atlantida','las-toscas','fortin-de-santa-rosa'], 'desc'=>'Atlántida es el principal balneario de la Costa de Oro, con casas, edificios bajos, hoteles, comercios y locales gastronómicos. Conviven instalaciones antiguas de veraneo con comercios que necesitan tableros y circuitos preparados para la temporada.'],
    'estacion-atlantida' => ['nombre'=>'Estación Atlántida', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['atlantida','las-toscas'], 'desc'=>'Estación Atlántida tiene casas con terreno, viviendas familiares y emprendimientos al norte de la Interbalnearia. Es habitual trabajar instalaciones completas para casas nuevas, bombas y tramos aéreos.'],
    'las-toscas' => ['nombre'=>'Las Toscas', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['atlantida','parque-del-plata','estacion-atlantida'], 'desc'=>'Las Toscas es un balneario de casas con jardín y viviendas permanentes entre Atlántida y Parque del Plata. Las instalaciones suelen ser de veraneo y necesitan tableros con disyuntor y circuitos nuevos para el uso diario.'],
    'parque-del-plata' => ['nombre'=>'Parque del Plata', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['las-toscas','la-floresta'], 'desc'=>'Parque del Plata combina casas de veraneo, viviendas permanentes, comercios y una zona de chacras al norte de la ruta. Las consultas frecuentes son reparaciones en instalaciones antiguas, bombas, portones y tableros renovados.'],
    'la-floresta' => ['nombre'=>'La Floresta', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['parque-del-plata','costa-azul','estacion-la-floresta'], 'desc'=>'La Floresta tiene casas de veraneo de distintas épocas, chalets reformados y viviendas permanentes entre pinos. Es habitual adaptar instalaciones antiguas, sumar protecciones y renovar tramos exteriores dañados por la humedad.'],
    'estacion-la-floresta' => ['nombre'=>'Estación La Floresta', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['la-floresta','costa-azul'], 'desc'=>'Estación La Floresta es una zona de casas con terreno y chacras al norte de la Interbalnearia. Las instalaciones suelen incluir bombas, galpones y tramos aéreos que conviene proteger correctamente.'],
    'costa-azul' => ['nombre'=>'Costa Azul', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['la-floresta','bello-horizonte','estacion-la-floresta'], 'desc'=>'Costa Azul es un balneario de casas con jardín, viviendas de fin de semana y familias que viven todo el año. Las consultas más comunes son reparaciones por humedad, tableros antiguos y circuitos nuevos para equipos actuales.'],
    'bello-horizonte' => ['nombre'=>'Bello Horizonte', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['costa-azul','guazuvira'], 'desc'=>'Bello Horizonte tiene casas de veraneo, viviendas permanentes y calles tranquilas junto a la playa. Es frecuente trabajar instalaciones de temporada, bombas y renovación de tableros y tramos exteriores.'],
    'guazuvira' => ['nombre'=>'Guazuvirá', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['bello-horizonte','san-luis'], 'desc'=>'Guazuvirá es un balneario tranquilo de casas entre pinos y viviendas de fin de semana. Las instalaciones suelen ser antiguas, con tramos aéreos y tableros chicos que conviene renovar para el uso permanente.'],
    'san-luis' => ['nombre'=>'San Luis', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['guazuvira','araminda','los-titanes'], 'desc'=>'San Luis combina casas de veraneo, viviendas permanentes y comercios chicos junto a la playa. Las consultas frecuentes son reparaciones por humedad y salinidad, bombas y tableros con disyuntor.'],
    'araminda' => ['nombre'=>'Araminda', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['san-luis','santa-lucia-del-este','los-titanes'], 'desc'=>'Araminda es un balneario de casas entre pinos y viviendas de fin de semana con población permanente en crecimiento. Es habitual trabajar instalaciones antiguas de veraneo, tramos exteriores y tableros nuevos.'],
    'santa-lucia-del-este' => ['nombre'=>'Santa Lucía del Este', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['araminda','biarritz','cuchilla-alta'], 'desc'=>'Santa Lucía del Este tiene casas de veraneo, viviendas permanentes y calles de arena junto a la playa. Las instalaciones suelen tener tramos aéreos, bombas y tableros chicos que necesitan protecciones nuevas.'],
    'biarritz' => ['nombre'=>'Biarritz', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['santa-lucia-del-este','cuchilla-alta'], 'desc'=>'Biarritz es un balneario pequeño de casas entre pinos y viviendas de fin de semana. Es frecuente adaptar instalaciones de temporada al uso diario, sumar circuitos y renovar tableros antiguos.'],
    'cuchilla-alta' => ['nombre'=>'Cuchilla Alta', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['biarritz','santa-ana','santa-lucia-del-este'], 'desc'=>'Cuchilla Alta combina casas de veraneo, viviendas permanentes y comercios chicos sobre la Interbalnearia. Las consultas habituales son reparaciones por humedad, bombas, portones y tableros con disyuntor.'],
    'santa-ana' => ['nombre'=>'Santa Ana', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['cuchilla-alta','balneario-argentino','jaureguiberry'], 'desc'=>'Santa Ana es un balneario de casas entre pinos con viviendas de fin de semana y familias permanentes. Las instalaciones suelen ser antiguas, con tramos aéreos y tableros que conviene renovar.'],
    'balneario-argentino' => ['nombre'=>'Balneario Argentino', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['santa-ana','jaureguiberry'], 'desc'=>'Balneario Argentino tiene casas de veraneo, viviendas permanentes y calles tranquilas junto a la playa. Es habitual trabajar instalaciones de temporada, bombas y renovación de tableros y tramos exteriores.'],
    'jaureguiberry' => ['nombre'=>'Jaureguiberry', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['balneario-argentino','santa-ana'], 'desc'=>'Jaureguiberry es el último balneario de Canelones sobre la Interbalnearia, con casas entre pinos, viviendas de fin de semana y población permanente. Las consultas frecuentes son reparaciones por humedad y salinidad, bombas y tableros nuevos.'],
    'los-titanes' => ['nombre'=>'Los Titanes', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['san-luis','araminda','la-tuna'], 'desc'=>'Los Titanes es un balneario de casas con jardín y viviendas de fin de semana en la Costa de Oro. Las instalaciones suelen ser de veraneo, con tramos exteriores y tableros chicos que necesitan protecciones nuevas.'],
    'la-tuna' => ['nombre'=>'La Tuna', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>['los-titanes','san-luis'], 'desc'=>'La Tuna combina casas de veraneo, viviendas permanentes y calles de arena cerca de la playa. Es frecuente adaptar instalaciones antiguas al uso diario, sumar circuitos y renovar tableros.'],
    'empalme-olmos' => ['nombre'=>'Empalme Olmos', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['pando','colonia-nicolich','barros-blancos'], 'desc'=>'Empalme Olmos tiene casas con terreno, viviendas familiares, talleres y comercios sobre Ruta 8. Las instalaciones suelen incluir galpones, bombas y ampliaciones que necesitan tableros y circuitos propios.'],
    'pando' => ['nombre'=>'Pando', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['empalme-olmos','barros-blancos','joaquin-suarez'], 'desc'=>'Pando es una ciudad con casco antiguo, casas de una y dos plantas, comercios muy activos e industrias en las afueras. Conviven instalaciones antiguas del centro con viviendas nuevas y locales que necesitan tableros dimensionados para su actividad.'],
    'barros-blancos' => ['nombre'=>'Barros Blancos', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['pando','empalme-olmos','joaquin-suarez','toledo'], 'desc'=>'Barros Blancos es una de las localidades más pobladas de Canelones, con casas con terreno, viviendas en construcción, cooperativas y comercios sobre Ruta 8. Las consultas frecuentes son instalaciones completas, ampliaciones y tableros con disyuntor.'],
    'joaquin-suarez' => ['nombre'=>'Joaquín Suárez', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['pando','barros-blancos','toledo','sauce'], 'desc'=>'Joaquín Suárez tiene casas con terreno, chacras y viviendas familiares en crecimiento. Es habitual trabajar instalaciones extensas con bombas, galpones, portones y tramos aéreos que requieren protecciones adecuadas.'],
    'toledo' => ['nombre'=>'Toledo', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['joaquin-suarez','barros-blancos','sauce','toledo-chico'], 'desc'=>'Toledo combina casas con terreno, viviendas nuevas, quintas y comercios de barrio en el límite con Montevideo. Las consultas habituales son instalaciones completas para casas en construcción, bombas y tableros nuevos.'],
    'sauce' => ['nombre'=>'Sauce', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['toledo','joaquin-suarez','santa-rosa'], 'desc'=>'Sauce es una ciudad de casas bajas con terreno, comercios sobre las calles principales y zonas de chacras alrededor. Es frecuente trabajar instalaciones antiguas del casco urbano y tramos extensos con bombas y galpones en las afueras.'],
    'las-piedras' => ['nombre'=>'Las Piedras', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['la-paz','progreso','18-de-mayo','colon'], 'desc'=>'Las Piedras es la ciudad más grande de Canelones, con un centro comercial muy activo, casas de una y dos plantas, edificios bajos y barrios en expansión. Conviven instalaciones antiguas del centro con viviendas nuevas y locales que necesitan tableros y circuitos preparados.'],
    'la-paz' => ['nombre'=>'La Paz', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['las-piedras','colon','18-de-mayo'], 'desc'=>'La Paz tiene casas antiguas, PH, viviendas familiares y comercios sobre César Mayo Gutiérrez, en el límite con Montevideo. Las instalaciones suelen ser de muchos años, con tableros con fusibles y ampliaciones hechas por etapas.'],
    '18-de-mayo' => ['nombre'=>'18 de Mayo', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['las-piedras','la-paz','progreso'], 'desc'=>'18 de Mayo es una localidad de casas con terreno, viviendas en construcción y comercios de barrio entre Las Piedras y La Paz. Es habitual trabajar instalaciones completas, ampliaciones y tableros con disyuntor.'],
    'progreso' => ['nombre'=>'Progreso', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['las-piedras','18-de-mayo','juanico'], 'desc'=>'Progreso combina casas con terreno, viviendas familiares, chacras y comercios sobre Ruta 5. Las consultas frecuentes son instalaciones para casas nuevas, bombas, galpones y tableros que quedaron chicos.'],
    'juanico' => ['nombre'=>'Juanicó', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['progreso','canelones'], 'desc'=>'Juanicó es una localidad de casas bajas rodeada de viñedos y chacras. Es habitual trabajar instalaciones extensas con bombas de riego, galpones y tramos aéreos, además de viviendas que necesitan tableros nuevos.'],
    'canelones' => ['nombre'=>'Canelones', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['juanico','santa-lucia','los-cerrillos','san-ramon'], 'desc'=>'La ciudad de Canelones tiene un casco histórico con casas antiguas, oficinas públicas, comercios y barrios de viviendas familiares alrededor. Conviven instalaciones de muchos años con tableros con fusibles y viviendas nuevas que necesitan instalación completa.'],
    'santa-lucia' => ['nombre'=>'Santa Lucía', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['canelones','aguas-corrientes','los-cerrillos'], 'desc'=>'Santa Lucía es una ciudad de casas antiguas de una planta, casonas, comercios y quintas junto al río. Las instalaciones suelen ser de muchos años y conviven con viviendas de fin de semana que necesitan tableros y protecciones nuevas.'],
    'aguas-corrientes' => ['nombre'=>'Aguas Corrientes', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['santa-lucia','los-cerrillos'], 'desc'=>'Aguas Corrientes es un pueblo de casas bajas junto al río Santa Lucía, con viviendas permanentes y de fin de semana. Es frecuente trabajar instalaciones antiguas, bombas, tramos exteriores y tableros nuevos.'],
    'los-cerrillos' => ['nombre'=>'Los Cerrillos', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['canelones','santa-lucia','aguas-corrientes'], 'desc'=>'Los Cerrillos combina casas con terreno, chacras y viviendas familiares en una zona rural cercana a Canelones. Las instalaciones suelen incluir bombas, galpones y tramos aéreos que requieren protecciones adecuadas.'],
    'san-ramon' => ['nombre'=>'San Ramón', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['canelones','san-bautista','santa-rosa'], 'desc'=>'San Ramón es una ciudad de casas bajas con terreno, comercios sobre las calles principales y chacras alrededor. Es habitual trabajar instalaciones antiguas del casco urbano y tramos extensos con bombas y galpones.'],
    'san-bautista' => ['nombre'=>'San Bautista', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['san-ramon','santa-rosa','san-antonio'], 'desc'=>'San Bautista tiene casas bajas con terreno, comercios de pueblo y una zona rural de granjas y chacras. Las consultas frecuentes son instalaciones para viviendas y galpones, bombas y tableros renovados.'],
    'san-antonio' => ['nombre'=>'San Antonio', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['san-bautista','santa-rosa','tala'], 'desc'=>'San Antonio es una localidad de casas bajas con terreno rodeada de chacras y granjas. Es habitual trabajar instalaciones extensas con bombas de riego, galpones y tramos aéreos, además de viviendas con tableros antiguos.'],
    'santa-rosa' => ['nombre'=>'Santa Rosa', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['sauce','san-ramon','san-bautista','san-antonio','san-jacinto'], 'desc'=>'Santa Rosa combina casas bajas con terreno, comercios de pueblo y una zona de chacras y granjas alrededor. Las instalaciones suelen incluir bombas, galpones y tramos exteriores que conviene proteger y ordenar.'],
    'san-jacinto' => ['nombre'=>'San Jacinto', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['santa-rosa','tala','migues'], 'desc'=>'San Jacinto es una localidad de casas con terreno sobre Ruta 7, con comercios de pueblo y zona rural alrededor. Es frecuente trabajar instalaciones para viviendas, galpones, bombas y tableros con disyuntor.'],
    'tala' => ['nombre'=>'Tala', 'depto'=>'Canelones', 'tipo'=>'antiguo', 'vecinos'=>['san-jacinto','san-antonio','migues'], 'desc'=>'Tala es una ciudad de casas bajas con terreno, comercios sobre la avenida principal y chacras alrededor. Conviven instalaciones antiguas del casco urbano con viviendas nuevas que necesitan instalación completa y tableros dimensionados.'],
    'migues' => ['nombre'=>'Migues', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['tala','san-jacinto','montes'], 'desc'=>'Migues es un pueblo de casas bajas con terreno y zona rural de chacras y ganadería. Es habitual trabajar instalaciones extensas con bombas, galpones y tramos aéreos, además de viviendas con tableros antiguos.'],
    'montes' => ['nombre'=>'Montes', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['migues','soca'], 'desc'=>'Montes es una localidad de casas bajas con terreno rodeada de chacras. Las consultas frecuentes son instalaciones para viviendas y galpones, bombas de agua y renovación de tableros.'],
    'soca' => ['nombre'=>'Soca', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['montes','piedras-de-afilar'], 'desc'=>'Soca es un pueblo de casas bajas con terreno, comercios chicos y chacras alrededor, cerca de la Costa de Oro. Es habitual trabajar instalaciones antiguas, bombas, galpones y tableros nuevos.'],
    'piedras-de-afilar' => ['nombre'=>'Piedras de Afilar', 'depto'=>'Canelones', 'tipo'=>'periferia', 'vecinos'=>['soca','estacion-la-floresta'], 'desc'=>'Piedras de Afilar es una localidad rural de casas dispersas, chacras y viviendas de fin de semana. Las instalaciones suelen incluir tramos aéreos largos, bombas y galpones que requieren protecciones adecuadas.'],
];

$servicio_base_slug = ['reparaciones'=>'reparaciones-electricas', 'instalaciones'=>'instalaciones-electricas', 'tableros'=>'tableros-electricos', 'iluminacion'=>'iluminacion', 'mantenimiento'=>'mantenimiento-electrico', 'comercios'=>'electricista-comercios', 'cargadores'=>'cargador-vehiculo-electrico'];


// Zonas con página propia (fase 1). El resto de las zonas se atiende desde /zonas y sus URLs antiguas redirigen con 301.
// Para sumar una zona: completar el brief de datos reales (tiempos, trabajos, reseñas, precios) y agregarla acá en tandas de 5 a 10.
// Pendiente del operador para estas zonas: tiempo de llegada, trabajos hechos con foto y reseñas reales del barrio.
$zonas_activas = [
    'pocitos' => [
        'nombre'=>'Pocitos', 'depto'=>'Montevideo', 'tipo'=>'torres', 'vecinos'=>['punta-carretas','buceo','cordon','villa-dolores'],
        'title'=>'Electricista en Pocitos – Apartamentos y edificios',
        'description'=>'Electricista a domicilio en Pocitos: térmicas que saltan, tableros chicos, circuitos para aire acondicionado y cargadores. Presupuesto por WhatsApp.',
        'intro'=>'Electricistas Montevideo atiende reparaciones, tableros e instalaciones en apartamentos, edificios y casas de Pocitos. Escribinos por WhatsApp con la dirección aproximada y una foto del tablero o del problema: te orientamos, te pasamos el presupuesto sin costo y coordinamos la visita, incluida la autorización del edificio cuando el trabajo toca espacios comunes.',
        'secciones'=>[
            ['h2'=>'¿Qué fallas eléctricas son comunes en los apartamentos de Pocitos?', 'p'=>['En Pocitos conviven torres de varias décadas, edificios nuevos y casas de una o dos plantas en las calles interiores. Muchos apartamentos se reformaron más de una vez y la instalación no siempre acompañó: la cocina, el aire acondicionado y el termotanque terminan colgados del mismo circuito, y la térmica salta cuando coinciden.', 'Otro caso frecuente es el tablero chico, pensado para el consumo de otra época, sin lugar para sumar circuitos ni disyuntor diferencial. En edificios con años también aparecen tomacorrientes sin conductor de tierra. Separar circuitos, ampliar el tablero y verificar la puesta a tierra resuelve la mayoría de estos problemas de raíz.']],
            ['h2'=>'¿Cómo se coordina un trabajo eléctrico en un edificio de Pocitos?', 'p'=>['Si el trabajo queda dentro de tu unidad, alcanza con coordinar el horario con vos y avisar en portería. Cuando hay que pasar cables por un ducto común, llegar al medidor en planta baja o trabajar en la cochera, la administración suele pedir un aviso previo y, a veces, una descripción del trabajo. Te ayudamos a prepararla.', 'Los cortes se hacen sobre la llave de tu apartamento, sin afectar ascensores, bombas ni la iluminación común del edificio.']],
            ['h2'=>'¿Se puede instalar un cargador de auto eléctrico en una cochera de Pocitos?', 'p'=>['En general sí. El punto de carga se alimenta desde el medidor de tu unidad hasta la cochera, con un circuito dedicado y sus protecciones propias. Lo que define el trabajo es el recorrido por espacios comunes y la potencia contratada. Los detalles están en la página de [cargadores para vehículos eléctricos](cargador-vehiculo-electrico-montevideo).']],
        ],
        'faq'=>[
            ['q'=>'¿Trabajan en edificios con portería en Pocitos?', 'a'=>'Sí. Coordinamos el horario con vos y con la portería, y si el trabajo pasa por espacios comunes te ayudamos con el aviso a la administración.'],
            ['q'=>'¿Por qué salta la térmica cuando prendo el aire acondicionado?', 'a'=>'Suele ser un circuito compartido con otros equipos de consumo alto. La solución habitual es un circuito dedicado para el aire con su propia térmica.'],
            ['q'=>'¿Cómo pido presupuesto para un trabajo en Pocitos?', 'a'=>'Escribinos por WhatsApp con la dirección aproximada, si es apartamento o casa, y una foto del tablero o del punto con problemas.'],
        ],
    ],
    'carrasco' => [
        'nombre'=>'Carrasco', 'depto'=>'Montevideo', 'tipo'=>'casas', 'vecinos'=>['punta-gorda','carrasco-norte','malvin'],
        'title'=>'Electricista en Carrasco – Casas, tableros y jardín',
        'description'=>'Electricista a domicilio en Carrasco: tableros de casas grandes, iluminación de jardín y cargadores para autos eléctricos. Presupuesto por WhatsApp.',
        'intro'=>'Electricistas Montevideo trabaja en casas y apartamentos de Carrasco: reparaciones, cambio de tableros, iluminación exterior y cargadores para autos eléctricos. Contanos por WhatsApp qué necesitás y mandanos una foto del tablero: te orientamos, te pasamos el presupuesto sin costo y coordinamos la visita.',
        'secciones'=>[
            ['h2'=>'¿Qué trabajos eléctricos piden más las casas de Carrasco?', 'p'=>['Las casas de Carrasco suelen tener varias ampliaciones, jardín y equipos que se fueron sumando con los años: aire acondicionado en cada dormitorio, bomba de piscina, portón automático, riego e iluminación exterior. Cada agregado sumó un circuito, y muchas veces el tablero quedó desordenado o al límite de su capacidad.', 'Un trabajo habitual es relevar la instalación completa, ordenar e identificar los circuitos, separar los exteriores con su propio disyuntor diferencial y, si hace falta, sumar un tablero secundario para el fondo o el garaje.']],
            ['h2'=>'¿Qué hay que tener en cuenta en la iluminación y los circuitos del jardín?', 'p'=>['Todo lo que queda a la intemperie necesita equipos con grado de protección adecuado para el agua y el polvo, cajas estancas y canalizaciones enterradas o protegidas. Los circuitos exteriores deben tener disyuntor diferencial, porque la humedad es la causa más común de fugas a tierra.', 'Si el diferencial salta cuando llueve, casi siempre hay una caja exterior con agua o un cable con la aislación dañada. Lo buscamos por tramos hasta encontrarlo. Más detalles en [iluminación](iluminacion-montevideo) y [reparaciones eléctricas](reparaciones-electricas-montevideo).']],
            ['h2'=>'¿Cómo es instalar un cargador de auto eléctrico en una casa con garaje?', 'p'=>['En una casa con garaje el trabajo suele ser directo: circuito dedicado desde el tablero, protecciones propias y el cargador en la pared, o en un poste si el auto queda afuera. Si el tablero está al límite, se amplía en el mismo trabajo. Mirá la página de [cargadores para vehículos eléctricos](cargador-vehiculo-electrico-montevideo).']],
        ],
        'faq'=>[
            ['q'=>'¿Por qué salta el disyuntor cuando llueve?', 'a'=>'Casi siempre hay agua en una caja exterior o un cable dañado en el jardín. Se revisan los circuitos exteriores por tramos hasta encontrar la fuga.'],
            ['q'=>'¿Pueden sumar un tablero para el garaje o el fondo?', 'a'=>'Sí. Cuando hay varios equipos lejos del tablero principal, un tablero secundario con sus propias protecciones ordena la instalación.'],
            ['q'=>'¿Atienden Carrasco Norte y Punta Gorda?', 'a'=>'Sí. Contanos la dirección aproximada por WhatsApp para coordinar la visita.'],
        ],
    ],
    'centro' => [
        'nombre'=>'Centro', 'en'=>'el Centro', 'depto'=>'Montevideo', 'tipo'=>'antiguo', 'vecinos'=>['cordon','ciudad-vieja','barrio-sur','aguada'],
        'title'=>'Electricista en el Centro – Edificios antiguos y locales',
        'description'=>'Electricista en el Centro de Montevideo: instalaciones viejas, tableros con fusibles, oficinas y locales. Presupuesto sin costo por WhatsApp.',
        'intro'=>'Electricistas Montevideo atiende apartamentos, oficinas y locales del Centro de Montevideo: reparaciones, renovación de instalaciones antiguas, tableros y electricidad para comercios. Escribinos por WhatsApp con la dirección aproximada y qué necesitás resolver: te pasamos el presupuesto sin costo y coordinamos un horario que no frene tu actividad.',
        'secciones'=>[
            ['h2'=>'¿Qué problemas tienen las instalaciones de los edificios antiguos del Centro?', 'p'=>['Buena parte del Centro son edificios de principios y mediados del siglo XX, con techos altos, paredes gruesas y varias reformas encima. Es común encontrar cables viejos con la aislación reseca, empalmes precarios dentro de las cajas, tableros con fusibles o sin disyuntor diferencial y ninguna puesta a tierra.', 'Son instalaciones que funcionan hasta que se les pide más consumo: un aire acondicionado, un horno eléctrico o una estufa. En ese momento aparecen las térmicas que saltan, los tomacorrientes que calientan o el olor a quemado.']],
            ['h2'=>'¿Conviene renovar toda la instalación o solo un tramo?', 'p'=>['Depende del estado de los cables y del tablero. Si la aislación está reseca en varios puntos, arreglar de a uno no alcanza y conviene renovar por circuitos, empezando por la cocina y los ambientes con más consumo. Si el problema está en el tablero, cambiarlo por uno con térmicas, diferencial y puesta a tierra suele ser el primer paso.', 'En paredes difíciles de canalizar se pueden usar canalizaciones exteriores prolijas. Lo evaluamos en la visita. Más información en [tableros eléctricos](tableros-electricos-montevideo) e [instalaciones eléctricas](instalaciones-electricas-montevideo).']],
            ['h2'=>'¿Trabajan en oficinas y locales del Centro fuera del horario comercial?', 'p'=>['Sí, se puede coordinar. En locales y oficinas planificamos los trabajos por etapas o en horarios en que no hay atención al público, y dejamos los circuitos identificados para el uso diario. Mirá la página de [electricidad para comercios](electricista-comercios-montevideo).']],
        ],
        'faq'=>[
            ['q'=>'Mi apartamento tiene tablero con fusibles, ¿hay que cambiarlo?', 'a'=>'Conviene. Un tablero con térmicas, disyuntor diferencial y puesta a tierra protege los cables, los equipos y a las personas, algo que los fusibles solos no hacen.'],
            ['q'=>'¿Pueden trabajar en un local sin cerrarlo?', 'a'=>'En general sí, organizando el trabajo por etapas o fuera del horario de atención.'],
            ['q'=>'¿Atienden Ciudad Vieja, Cordón y Barrio Sur?', 'a'=>'Sí. Indicanos la dirección aproximada por WhatsApp para coordinar.'],
        ],
    ],
    'ciudad-de-la-costa' => [
        'nombre'=>'Ciudad de la Costa', 'depto'=>'Canelones', 'tipo'=>'casas', 'vecinos'=>[],
        'cubre'=>['shangrila','san-jose-de-carrasco','lagomar','solymar','lomas-de-solymar','colinas-de-solymar','el-pinar'],
        'title'=>'Electricista en Ciudad de la Costa – Solymar a El Pinar',
        'description'=>'Electricista a domicilio en Ciudad de la Costa: Shangrilá, Lagomar, Solymar y El Pinar. Tableros, ampliaciones y cargadores. Presupuesto por WhatsApp.',
        'intro'=>'Electricistas Montevideo trabaja en casas y comercios de Ciudad de la Costa, desde Shangrilá y San José de Carrasco hasta Lagomar, Solymar y El Pinar. Reparaciones, cambio de tableros, instalaciones para ampliaciones y cargadores para autos eléctricos. Escribinos por WhatsApp con tu zona y una foto del problema, y te pasamos el presupuesto sin costo.',
        'secciones'=>[
            ['h2'=>'¿Qué zonas de Ciudad de la Costa atendemos?', 'p'=>['Atendemos Shangrilá, San José de Carrasco, Lagomar, Solymar, Lomas y Colinas de Solymar y El Pinar. Si estás en Paso Carrasco, Barra de Carrasco o Colonia Nicolich, consultanos igual: indicanos la dirección aproximada al escribir.']],
            ['h2'=>'¿Por qué las casas de la Costa tienen tableros al límite?', 'p'=>['Muchas casas de Ciudad de la Costa empezaron como vivienda de fin de semana y se fueron ampliando para vivir todo el año. El consumo creció, con aire acondicionado, termotanque, estufa eléctrica y cocina, pero el tablero y la acometida quedaron como estaban. El resultado son térmicas que saltan en invierno o verano, circuitos compartidos y ampliaciones colgadas de cualquier tomacorriente.', 'La solución pasa por relevar el consumo real, separar circuitos, ampliar o cambiar el tablero y, si hace falta, revisar la potencia contratada con UTE. Más información en [tableros eléctricos](tableros-electricos-montevideo).']],
            ['h2'=>'¿Qué hacer con la humedad en cajas y tramos exteriores?', 'p'=>['La cercanía del mar y la humedad deterioran las cajas, los tomacorrientes exteriores y las conexiones de portones, bombas e iluminación del jardín. Los síntomas típicos son un disyuntor que salta con la lluvia o un circuito exterior que falla por temporadas. Se revisa por tramos, se cambian las cajas por estancas y se protegen los empalmes.']],
            ['h2'=>'¿Se puede cargar un auto eléctrico en casa en Ciudad de la Costa?', 'p'=>['Sí. En casas con garaje o entrada para el auto se instala un circuito dedicado desde el tablero con sus protecciones y un cargador en la pared. Los detalles están en [cargadores para vehículos eléctricos](cargador-vehiculo-electrico-montevideo).']],
        ],
        'faq'=>[
            ['q'=>'¿Atienden Solymar, Lagomar y El Pinar?', 'a'=>'Sí. Escribinos por WhatsApp con la dirección aproximada para coordinar la visita.'],
            ['q'=>'Me salta la térmica en invierno cuando prendo la estufa, ¿qué puede ser?', 'a'=>'Lo más común es un circuito compartido con otros equipos de consumo alto. Separar circuitos o ampliar el tablero suele resolverlo.'],
            ['q'=>'¿Necesito aumentar la potencia contratada con UTE?', 'a'=>'No siempre. Primero se revisa el consumo real y cómo están repartidos los circuitos. Si hace falta, te orientamos sobre el trámite.'],
        ],
    ],
    'costa-de-oro' => [
        'nombre'=>'Costa de Oro', 'en'=>'la Costa de Oro', 'depto'=>'Canelones', 'tipo'=>'balneario', 'vecinos'=>[],
        'cubre'=>['neptunia','pinamar','salinas','marindia','fortin-de-santa-rosa','villa-argentina','atlantida','estacion-atlantida','las-toscas','parque-del-plata','la-floresta','estacion-la-floresta','costa-azul','bello-horizonte','guazuvira','san-luis','araminda','santa-lucia-del-este','biarritz','cuchilla-alta','santa-ana','balneario-argentino','jaureguiberry','los-titanes','la-tuna'],
        'title'=>'Electricista en la Costa de Oro – Atlántida a La Floresta',
        'description'=>'Electricista en la Costa de Oro: Salinas, Atlántida, Parque del Plata y La Floresta. Casas de veraneo, humedad y comercios. Presupuesto por WhatsApp.',
        'intro'=>'Electricistas Montevideo atiende casas y comercios de la Costa de Oro, de Neptunia y Salinas a Atlántida, Parque del Plata, La Floresta y los balnearios hacia Jaureguiberry. Reparaciones, revisión de casas de veraneo, tableros e instalaciones. Escribinos por WhatsApp con el balneario y una foto del problema, y te pasamos el presupuesto sin costo.',
        'secciones'=>[
            ['h2'=>'¿En qué balnearios de la Costa de Oro trabajamos?', 'p'=>['Neptunia, Pinamar, Salinas, Marindia, Villa Argentina, Atlántida, Las Toscas, Parque del Plata, La Floresta, Costa Azul, Bello Horizonte, San Luis, Santa Lucía del Este, Biarritz, Cuchilla Alta y los balnearios hasta Jaureguiberry. Confirmá tu dirección aproximada al escribir para coordinar la visita.']],
            ['h2'=>'¿Qué revisar en una casa de veraneo antes de la temporada?', 'p'=>['Una casa que pasa meses cerrada acumula humedad en cajas y tomacorrientes, y a veces cables dañados por roedores. Antes de usarla conviene revisar que el disyuntor diferencial funcione, probar la puesta a tierra, mirar las cajas exteriores y confirmar que la bomba de agua y el termotanque arrancan sin hacer saltar las protecciones.', 'Si la casa queda cerrada, lo más seguro es bajar la llave general o dejar encendidos solo los circuitos que hacen falta, como una alarma o la heladera. Más detalles en [revisión y mantenimiento](mantenimiento-electrico-montevideo).']],
            ['h2'=>'¿Por qué salta el disyuntor en las casas cerca del mar?', 'p'=>['La humedad y la salinidad son la causa más frecuente de fugas a tierra en la Costa de Oro: cajas exteriores con agua, borneras oxidadas o un equipo del jardín con la aislación dañada. El disyuntor diferencial corta justamente para evitar una descarga. En lugar de subirlo una y otra vez, hay que encontrar el circuito con la fuga. Mirá [reparaciones eléctricas](reparaciones-electricas-montevideo).']],
            ['h2'=>'¿Atienden comercios de temporada?', 'p'=>['Sí. Los comercios de balneario trabajan al máximo en verano, con heladeras, freezers, aire acondicionado e iluminación funcionando a la vez. Conviene preparar el tablero y los circuitos antes de la temporada. Más información en [electricidad para comercios](electricista-comercios-montevideo).']],
        ],
        'faq'=>[
            ['q'=>'¿Atienden La Floresta y Parque del Plata?', 'a'=>'Sí. Escribinos por WhatsApp con la dirección aproximada para coordinar la visita.'],
            ['q'=>'¿Pueden revisar la casa de veraneo antes de que lleguemos?', 'a'=>'Se puede coordinar. Contanos por WhatsApp cómo acceder y qué querés revisar.'],
            ['q'=>'¿Por qué el disyuntor salta solo cuando llueve?', 'a'=>'Suele haber agua en una caja exterior o un cable dañado. Se revisan los circuitos exteriores por tramos hasta encontrar la fuga.'],
        ],
    ],
];

foreach ($zonas_activas as $zk => $z) {
    $pages['electricista-' . $zk] = ['title'=>$z['title'], 'description'=>$z['description'], 'heading'=>'Electricista en ' . ($z['en'] ?? $z['nombre']), 'crumb'=>'Electricista en ' . ($z['en'] ?? $z['nombre']), 'barrio_hub'=>$zk, 'mod'=>'2026-09-25'];
}

// URL antigua de zona (hub o servicio × zona) → destino 301. Devuelve null si la ruta no es de zona.
// Si la zona ya tiene página propia (/zonas/{slug} o /{servicio}/{slug}), el 301 va ahí; si no, a la madre o al ancla de /zonas.
// Alias: claves antiguas de $barrios_perfil que hoy forman parte de un barrio oficial con otro slug.
if (!function_exists("zona_redireccion")) { function zona_redireccion(string $route, array $barrios_perfil, array $zonas_activas, array $servicio_base_slug, array $servicios_landing): ?string {
    $alias = ['figurita'=>'la-figurita', 'bella-vista'=>'capurro', 'villa-dolores'=>'parque-batlle', 'bolivar'=>'mercado-modelo', 'parque-guarani'=>'maronas', 'bella-italia'=>'punta-de-rieles', 'lavalleja'=>'penarol', 'goes'=>'villa-munoz', 'pajas-blancas'=>'casabo', 'melilla'=>'lezica', 'santiago-vazquez'=>'paso-de-la-arena'];
    foreach ($servicio_base_slug as $id => $base) {
        if (!str_starts_with($route, $base . '-')) continue;
        $zk = substr($route, strlen($base) + 1);
        if (!isset($barrios_perfil[$zk]) && !isset($zonas_activas[$zk])) continue;
        $zn = $alias[$zk] ?? $zk;
        if (function_exists('sz_publicada') && sz_publicada($id, $zn)) return sz_url($id, $zn);
        return $servicios_landing[$id]['slug'];
    }
    if (str_starts_with($route, 'electricista-')) {
        $zk = substr($route, 13);
        foreach ($zonas_activas as $ak => $z) if (in_array($zk, $z['cubre'] ?? [], true)) return 'electricista-' . $ak;
        $zn = $alias[$zk] ?? $zk;
        if (function_exists('zona_publicada') && zona_publicada($zn)) return zona_url($zn);
        if (isset($barrios_perfil[$zk])) return 'zonas#' . $zk;
    }
    return null;
} }
