<?php
// Landings por servicio. Sin precios, plazos, garantías ni datos no confirmados.

$servicios_landing = [
    'reparaciones' => [
        'slug' => 'reparaciones-electricas-montevideo',
        'hero' => 'Electricista a domicilio para fallas, llaves que saltan y tomacorrientes sin corriente. Presupuesto sin costo.',
        'title' => 'Reparaciones eléctricas en Montevideo | Electricista',
        'description' => 'Electricista a domicilio en Montevideo para llaves que saltan, cortocircuitos y tomacorrientes sin corriente. Presupuesto sin costo por WhatsApp.',
        'crumb' => 'Reparaciones eléctricas',
        'h1' => 'Reparaciones eléctricas en Montevideo',
        'intro' => 'Si en tu casa o comercio saltó la llave, un tomacorriente dejó de funcionar o una luz titila sin motivo, contanos qué pasa. Revisamos la falla, te explicamos la causa y te pasamos el presupuesto antes de tocar nada.',
        'lista_titulo' => 'Fallas que resolvemos',
        'lista' => [
            'Llave térmica o disyuntor que salta al encender un equipo o sin motivo aparente.',
            'Tomacorrientes, llaves de luz o puntos que quedaron sin corriente.',
            'Cortocircuitos, olor a quemado o cables recalentados en cajas y tableros.',
            'Luces que titilan, se apagan solas o bajan de intensidad al usar electrodomésticos.',
            'Sectores enteros de la casa sin energía mientras el resto funciona.',
            'Timbres, porteros eléctricos y bombas de agua que dejaron de andar.',
            'Cables sueltos, empalmes precarios o instalaciones viejas que dan problemas.',
        ],
        'secciones' => [
            ['h2' => 'Cómo trabajamos una reparación', 'p' => ['Empezamos por escucharte: qué falla, desde cuándo y qué estabas usando cuando ocurrió. Con eso ya sabemos por dónde buscar. Después revisamos el tablero, los circuitos involucrados y los puntos afectados con instrumentos de medición, no a ojo.', 'Cuando encontramos la causa te la mostramos y te explicamos las opciones. Reparar un cable dañado, reemplazar una térmica que ya no protege o corregir un empalme mal hecho son trabajos distintos, y el presupuesto se arma según lo que realmente necesita tu instalación.']],
            ['h2' => 'Por qué salta la llave', 'p' => ['Una llave térmica que salta está haciendo su trabajo: corta la corriente porque detectó una sobrecarga o un cortocircuito. Puede ser un electrodoméstico con falla, demasiados equipos en el mismo circuito o un cable con la aislación dañada. Si es el disyuntor diferencial el que corta, suele haber una fuga a tierra en algún artefacto o en la instalación.', 'Volver a subir la llave una y otra vez no soluciona el problema y puede empeorarlo. Si se repite, conviene que lo revise un electricista antes de que la falla afecte otros equipos.']],
            ['h2' => 'Qué conviene hacer mientras esperás', 'p' => ['Desconectá el equipo que estaba en uso cuando saltó la llave y no manipules cables ni abras el tablero. Si notás olor a quemado, chispas o un tomacorriente caliente, bajá la llave general y consultanos. Una foto del tablero o del punto con problemas nos ayuda a orientar la visita.']],
        ],
        'faq' => [
            ['q' => '¿Atienden reparaciones eléctricas a domicilio en toda Montevideo?', 'a' => 'Sí. Trabajamos en casas, apartamentos y comercios de Montevideo. Indicanos el barrio al consultar para confirmar la atención y coordinar la visita.'],
            ['q' => '¿Cuánto cuesta una reparación eléctrica?', 'a' => 'Depende de la falla, el alcance del trabajo y los materiales. Te pasamos el presupuesto sin costo después de entender el problema y antes de empezar.'],
            ['q' => '¿Qué hago si salta la llave y no vuelve a subir?', 'a' => 'No la fuerces. Desconectá los equipos del circuito afectado y consultanos por WhatsApp o teléfono para coordinar una revisión.'],
            ['q' => '¿Reparan instalaciones eléctricas viejas?', 'a' => 'Sí. Revisamos el estado de la instalación y te decimos si alcanza con una reparación puntual o si conviene renovar un tramo o el tablero.'],
        ],
        'wsp' => 'Hola, necesito una reparación eléctrica en Montevideo.',
    ],
    'instalaciones' => [
        'slug' => 'instalaciones-electricas-montevideo',
        'hero' => 'Instalaciones eléctricas para obra nueva, reformas y nuevos puntos en casas y comercios. Presupuesto sin costo.',
        'title' => 'Instalaciones eléctricas en Montevideo | Obra y reformas',
        'description' => 'Instalación eléctrica en Montevideo para obra nueva, reformas y nuevos puntos: cableado, tomacorrientes y circuitos. Presupuesto sin costo.',
        'crumb' => 'Instalaciones eléctricas',
        'h1' => 'Instalaciones eléctricas en Montevideo',
        'intro' => 'Estás reformando la cocina, sumando un dormitorio o armando un local nuevo y necesitás una instalación eléctrica hecha bien desde el principio. Planificamos los circuitos, tendemos el cableado y dejamos cada punto listo para usar.',
        'lista_titulo' => 'Trabajos de instalación',
        'lista' => [
            'Instalación eléctrica completa para viviendas, apartamentos y locales.',
            'Nuevos puntos de luz, tomacorrientes y llaves en ambientes existentes.',
            'Cableado y canalización para reformas y ampliaciones.',
            'Circuitos independientes para aire acondicionado, termotanque, horno y cocina eléctrica.',
            'Puesta a tierra y protecciones acordes a la instalación.',
            'Renovación de instalaciones antiguas con cables o tableros obsoletos.',
            'Preparación eléctrica para obra: bocas, cajas y conductos antes de cerrar paredes.',
        ],
        'secciones' => [
            ['h2' => 'Cómo planificamos una instalación', 'p' => ['Antes de tirar un solo cable, conversamos sobre cómo vas a usar cada ambiente: dónde van los electrodomésticos, cuántos tomacorrientes necesitás y qué equipos consumen más. Con eso definimos los circuitos, las secciones de cable y las protecciones para que la instalación no quede corta en unos años.', 'En reformas coordinamos con la obra para canalizar antes del revoque y evitar romper dos veces. Si la instalación existente está en buen estado, la aprovechamos; si no, te decimos qué tramos conviene renovar.']],
            ['h2' => 'Instalaciones nuevas y reformas', 'p' => ['En una obra nueva o una reforma completa, el trabajo incluye tablero, circuitos, cableado, bocas, cajas y la conexión de cada punto. En ampliaciones más chicas, como sumar un tomacorriente en la cocina o un punto de luz en el patio, evaluamos de qué circuito conviene tomar la alimentación para no sobrecargar lo que ya tenés.', 'También preparamos la instalación para equipos que exigen un circuito propio, como aires acondicionados, termotanques o cocinas eléctricas.']],
            ['h2' => 'Qué información nos sirve', 'p' => ['Un plano o un croquis del ambiente, fotos del tablero actual y una lista de lo que querés conectar. Con eso podemos orientarte y coordinar una visita para relevar la instalación y pasarte el presupuesto.']],
        ],
        'faq' => [
            ['q' => '¿Hacen la instalación eléctrica completa de una casa o apartamento?', 'a' => 'Sí. Planificamos y ejecutamos la instalación completa, desde el tablero hasta cada punto de luz y tomacorriente.'],
            ['q' => '¿Pueden agregar un tomacorriente o un punto de luz nuevo?', 'a' => 'Sí. Evaluamos de qué circuito conviene alimentarlo y lo instalamos con la canalización adecuada.'],
            ['q' => '¿Trabajan junto con albañiles u otros gremios en una reforma?', 'a' => 'Sí. Coordinamos con la obra para canalizar en el momento correcto y evitar romper de más.'],
            ['q' => '¿Cómo pido presupuesto para una instalación?', 'a' => 'Escribinos por WhatsApp con el barrio, el tipo de inmueble y lo que querés instalar. Si podés, sumá fotos o un croquis.'],
        ],
        'wsp' => 'Hola, quiero consultar por una instalación eléctrica en Montevideo.',
    ],
    'tableros' => [
        'slug' => 'tableros-electricos-montevideo',
        'hero' => 'Cambio e instalación de tableros con térmicas, disyuntor y puesta a tierra. Presupuesto sin costo.',
        'title' => 'Tableros eléctricos en Montevideo | Térmicas y disyuntor',
        'description' => 'Instalación y cambio de tableros eléctricos en Montevideo: llaves térmicas, disyuntor diferencial y puesta a tierra. Presupuesto sin costo.',
        'crumb' => 'Tableros y protecciones',
        'h1' => 'Tableros eléctricos en Montevideo',
        'intro' => 'El tablero es el corazón de tu instalación: ahí están las llaves térmicas y el disyuntor que protegen los cables, los equipos y a las personas. Si el tuyo es viejo, le faltan protecciones o salta seguido, revisarlo es el primer paso.',
        'lista_titulo' => 'Trabajos en tableros',
        'lista' => [
            'Instalación de tableros nuevos para viviendas, apartamentos y locales.',
            'Cambio de tableros antiguos con fusibles o sin disyuntor diferencial.',
            'Reemplazo de llaves térmicas que ya no protegen o saltan sin motivo.',
            'Instalación de disyuntor diferencial y puesta a tierra.',
            'Ampliación de tableros para sumar circuitos nuevos.',
            'Ordenamiento e identificación de circuitos.',
            'Revisión de conexiones flojas, cables recalentados y borneras.',
        ],
        'secciones' => [
            ['h2' => 'Térmicas, disyuntor y puesta a tierra', 'p' => ['La llave térmica protege los cables y los equipos de sobrecargas y cortocircuitos. El disyuntor diferencial protege a las personas: corta la corriente cuando detecta una fuga a tierra, por ejemplo cuando un artefacto tiene una falla de aislación. La puesta a tierra es la que le da sentido a ese disyuntor. Un tablero completo tiene las tres cosas dimensionadas para la instalación que alimenta.', 'Muchos tableros antiguos en Montevideo todavía tienen fusibles o una sola llave general para toda la casa. Renovarlo permite separar circuitos, sumar protecciones y saber qué llave corresponde a cada ambiente.']],
            ['h2' => 'Cuándo conviene cambiar el tablero', 'p' => ['Si tiene fusibles, si no tiene disyuntor diferencial, si las llaves saltan seguido, si notás marcas de recalentamiento o si vas a sumar equipos de consumo alto como aire acondicionado o cocina eléctrica. También cuando reformás y la cantidad de circuitos crece.', 'Antes de cambiarlo, revisamos la instalación aguas abajo: de nada sirve un tablero nuevo si los cables que salen de él están en mal estado.']],
            ['h2' => 'Cómo es el trabajo', 'p' => ['Relevamos el tablero actual y los circuitos, definimos las protecciones necesarias y te pasamos el presupuesto. El cambio se hace con la energía cortada y coordinando el horario para que el corte te moleste lo menos posible. Al terminar, cada llave queda identificada.']],
        ],
        'faq' => [
            ['q' => '¿Cambian tableros con fusibles por tableros con térmicas?', 'a' => 'Sí. Es uno de los trabajos más comunes en instalaciones antiguas de Montevideo.'],
            ['q' => '¿Qué es el disyuntor diferencial y por qué lo necesito?', 'a' => 'Es la protección que corta la corriente ante una fuga a tierra y evita descargas a las personas. Toda instalación debería tenerlo junto con una puesta a tierra.'],
            ['q' => '¿Por qué salta la térmica seguido?', 'a' => 'Puede ser una sobrecarga del circuito, un equipo con falla o una térmica desgastada. Lo revisamos para encontrar la causa antes de reemplazar nada.'],
            ['q' => '¿Cuánto tiempo se corta la luz al cambiar el tablero?', 'a' => 'Depende del tamaño del tablero y de la instalación. Lo coordinamos con vos al momento de presupuestar.'],
        ],
        'wsp' => 'Hola, quiero consultar por un tablero eléctrico en Montevideo.',
    ],
    'iluminacion' => [
        'slug' => 'iluminacion-montevideo',
        'hero' => 'Luminarias, spots, tiras LED e iluminación exterior para casas y comercios. Presupuesto sin costo.',
        'title' => 'Iluminación en Montevideo | Instalación de luces LED',
        'description' => 'Electricista para iluminación en Montevideo: luminarias, spots, tiras LED, luz exterior y cambio a LED. Presupuesto sin costo.',
        'crumb' => 'Iluminación',
        'h1' => 'Iluminación en Montevideo',
        'intro' => 'Una buena iluminación cambia cómo se ve y se usa un ambiente. Instalamos luminarias, spots, tiras LED y luces exteriores, y renovamos instalaciones viejas para pasar a LED sin perder calidad de luz.',
        'lista_titulo' => 'Trabajos de iluminación',
        'lista' => [
            'Instalación de luminarias, plafones y colgantes.',
            'Spots embutidos y rieles para living, cocina y comercios.',
            'Tiras LED en muebles, bajo mesada, cielorrasos y vidrieras.',
            'Iluminación exterior para patios, jardines, entradas y fachadas.',
            'Cambio de iluminación tradicional a LED.',
            'Nuevos puntos de luz y llaves combinadas o de escalera.',
            'Sensores de movimiento y luces con temporizador.',
        ],
        'secciones' => [
            ['h2' => 'Cómo elegir la iluminación', 'p' => ['No todas las luces sirven para todo. En una cocina conviene luz general más luz puntual sobre la mesada; en un living, capas de luz que se puedan combinar; en un comercio, iluminación que muestre el producto sin encandilar. Te ayudamos a definir la cantidad de puntos, la potencia y la temperatura de color según el uso de cada espacio.', 'Si ya tenés las luminarias elegidas, revisamos que la instalación las soporte y las conectamos. Si no, te orientamos sobre qué tipo conviene para lo que querés lograr.']],
            ['h2' => 'Pasar a LED', 'p' => ['Cambiar a LED reduce el consumo y la cantidad de veces que hay que cambiar lámparas. En muchos casos alcanza con reemplazar la lámpara; en otros, con luminarias viejas o transformadores para dicroicas, conviene renovar el artefacto o adaptar la instalación para que el LED funcione sin parpadeos.']],
            ['h2' => 'Iluminación exterior', 'p' => ['Las luces de patio, jardín y fachada necesitan artefactos y conexiones aptas para intemperie, además de una protección adecuada en el tablero. Instalamos apliques, farolas, reflectores y sensores de movimiento con las canalizaciones correctas para exteriores.']],
        ],
        'faq' => [
            ['q' => '¿Instalan luminarias que ya compré?', 'a' => 'Sí. Revisamos que la instalación sea compatible y las dejamos funcionando.'],
            ['q' => '¿Hacen instalación de tiras LED?', 'a' => 'Sí, en muebles, cielorrasos, bajo mesada, vidrieras y exteriores, con la fuente y la canalización adecuadas.'],
            ['q' => '¿Pueden agregar un punto de luz donde no hay?', 'a' => 'Sí. Evaluamos el recorrido de la canalización y la llave desde la que se va a comandar.'],
            ['q' => '¿Trabajan iluminación para comercios?', 'a' => 'Sí. Locales, vidrieras, oficinas y depósitos, coordinando horarios para no interrumpir la actividad.'],
        ],
        'wsp' => 'Hola, quiero consultar por iluminación en Montevideo.',
    ],
    'mantenimiento' => [
        'slug' => 'mantenimiento-electrico-montevideo',
        'hero' => 'Revisión completa de tu instalación eléctrica con informe claro. Presupuesto sin costo.',
        'title' => 'Mantenimiento eléctrico en Montevideo | Revisión',
        'description' => 'Revisión y mantenimiento de instalaciones eléctricas en Montevideo: tableros, cables y protecciones, con informe claro. Presupuesto sin costo.',
        'crumb' => 'Revisión y mantenimiento',
        'h1' => 'Revisión y mantenimiento eléctrico en Montevideo',
        'intro' => 'Vas a comprar o alquilar una propiedad, tu instalación tiene muchos años o simplemente querés saber en qué estado está. Hacemos una revisión completa y te decimos qué está bien, qué conviene corregir y qué puede esperar.',
        'lista_titulo' => 'Qué revisamos',
        'lista' => [
            'Tablero: protecciones, conexiones, señales de recalentamiento.',
            'Disyuntor diferencial y puesta a tierra.',
            'Estado de cables, empalmes y cajas de paso.',
            'Tomacorrientes, llaves y puntos de luz.',
            'Circuitos sobrecargados o mal distribuidos.',
            'Instalaciones de equipos de consumo alto.',
            'Mantenimiento periódico para comercios y edificios.',
        ],
        'secciones' => [
            ['h2' => 'Cuándo conviene una revisión', 'p' => ['Antes de mudarte a una propiedad, cuando la instalación tiene más de veinte años, después de una humedad o una filtración, si notás olores, calor en llaves o tomacorrientes, o si las luces cambian de intensidad. También cuando vas a sumar equipos y no sabés si la instalación aguanta.', 'Una revisión a tiempo suele evitar una reparación más grande después.']],
            ['h2' => 'Qué recibís', 'p' => ['Un informe claro de lo que encontramos, ordenado por urgencia: qué hay que resolver ahora, qué conviene planificar y qué está en condiciones. Si querés, te pasamos el presupuesto de las correcciones para que decidas cómo seguir.']],
            ['h2' => 'Mantenimiento para comercios', 'p' => ['Para locales, oficinas y edificios ofrecemos visitas periódicas para revisar tableros, iluminación y puntos de consumo alto, y resolver problemas antes de que interrumpan la actividad. Coordinamos los horarios según tu operación.']],
        ],
        'faq' => [
            ['q' => '¿Hacen revisiones antes de comprar o alquilar una propiedad?', 'a' => 'Sí. Revisamos la instalación y te informamos su estado para que decidas con información.'],
            ['q' => '¿La revisión incluye presupuesto de las reparaciones?', 'a' => 'Sí, si lo querés. Después del informe te pasamos el presupuesto de lo que convenga corregir.'],
            ['q' => '¿Cada cuánto conviene revisar una instalación?', 'a' => 'Depende de la antigüedad y el uso. En comercios y edificios se recomienda un control periódico; en viviendas, ante cualquier señal de falla o antes de una reforma.'],
            ['q' => '¿Revisan instalaciones de edificios y consorcios?', 'a' => 'Sí. Consultanos por espacios comunes, tableros generales e iluminación de edificios.'],
        ],
        'wsp' => 'Hola, quiero coordinar una revisión eléctrica en Montevideo.',
    ],
    'comercios' => [
        'slug' => 'electricista-comercios-montevideo',
        'hero' => 'Instalaciones, tableros e iluminación para locales y oficinas, sin frenar tu actividad. Presupuesto sin costo.',
        'title' => 'Electricista para comercios en Montevideo | Locales',
        'description' => 'Electricista para locales, oficinas y comercios en Montevideo: instalaciones, tableros, iluminación y mantenimiento. Presupuesto sin costo.',
        'crumb' => 'Electricidad para comercios',
        'h1' => 'Electricista para comercios en Montevideo',
        'intro' => 'Un local sin luz es un local cerrado. Atendemos comercios, oficinas, consultorios y depósitos de Montevideo con trabajos planificados para que tu actividad no se detenga: desde una reparación puntual hasta la instalación completa de un local nuevo.',
        'lista_titulo' => 'Trabajos para comercios',
        'lista' => [
            'Instalación eléctrica de locales nuevos y remodelaciones.',
            'Tableros comerciales con circuitos separados por sector.',
            'Iluminación de salón, vidriera, oficinas y depósitos.',
            'Circuitos para equipos de refrigeración, hornos, aire acondicionado y maquinaria.',
            'Tomacorrientes y puestos de trabajo para oficinas.',
            'Reparaciones urgentes y mantenimiento periódico.',
            'Ordenamiento de instalaciones improvisadas o crecidas sin planificación.',
        ],
        'secciones' => [
            ['h2' => 'Trabajar sin frenar tu negocio', 'p' => ['Coordinamos los trabajos fuera del horario de atención o por etapas para que puedas seguir operando. Antes de empezar definimos qué se corta, cuándo y por cuánto tiempo, y te lo comunicamos con anticipación.', 'En locales que fueron creciendo con el tiempo es común encontrar instalaciones improvisadas. Las ordenamos, separamos circuitos y dejamos el tablero identificado para que cualquier problema futuro sea fácil de ubicar.']],
            ['h2' => 'Instalación de un local nuevo', 'p' => ['Relevamos el local, conversamos sobre el equipamiento que vas a usar y proyectamos circuitos, tablero, iluminación y tomacorrientes según la actividad. Coordinamos con la obra y con los proveedores de equipos para que todo quede conectado y funcionando para la apertura.']],
            ['h2' => 'Oficinas y consultorios', 'p' => ['Puestos de trabajo con tomacorrientes suficientes, iluminación adecuada para pantallas, circuitos dedicados para equipos sensibles y protecciones correctas. Trabajos limpios y con la mínima interrupción para el equipo.']],
        ],
        'faq' => [
            ['q' => '¿Pueden trabajar fuera del horario comercial?', 'a' => 'Sí. Coordinamos los trabajos en el horario que menos afecte tu actividad.'],
            ['q' => '¿Hacen la instalación eléctrica completa de un local?', 'a' => 'Sí. Desde el tablero hasta la iluminación y los tomacorrientes, según la actividad y el equipamiento.'],
            ['q' => '¿Atienden urgencias en comercios?', 'a' => 'Llamanos para consultar la disponibilidad en ese momento y coordinar la atención.'],
            ['q' => '¿Ofrecen mantenimiento periódico para comercios?', 'a' => 'Sí. Consultanos para armar un plan de revisiones según tu local.'],
        ],
        'wsp' => 'Hola, quiero consultar por electricidad para mi comercio en Montevideo.',
    ],
    'cargadores' => [
        'slug' => 'cargador-vehiculo-electrico-montevideo',
        'hero' => 'Instalación de wallbox para auto eléctrico o híbrido en garaje, cochera o edificio. Presupuesto sin costo.',
        'title' => 'Cargadores para autos eléctricos en Montevideo | Wallbox',
        'description' => 'Instalación de cargador wallbox para auto eléctrico o híbrido en Montevideo y Canelones: garaje, cochera o edificio. Presupuesto sin costo.',
        'crumb' => 'Cargadores para vehículos eléctricos',
        'h1' => 'Instalación de cargadores para vehículos eléctricos en Montevideo',
        'intro' => 'Compraste un auto eléctrico o un híbrido enchufable y querés cargarlo en casa de forma segura y rápida. Instalamos el cargador (wallbox) o el punto de carga en tu garaje, cochera o edificio, con un circuito dedicado desde el tablero y las protecciones que exige un consumo de esta potencia.',
        'lista_titulo' => 'Qué incluye la instalación',
        'lista' => [
            'Relevamiento de la instalación: potencia contratada, tablero, distancia al punto de carga y tipo de vehículo.',
            'Circuito dedicado desde el tablero con cable de sección adecuada para la potencia del cargador.',
            'Protecciones propias: llave térmica y disyuntor diferencial del tipo requerido para carga de vehículos.',
            'Instalación y conexión del cargador wallbox o del tomacorriente de carga reforzado.',
            'Puesta a tierra verificada y canalización apta para garajes y exteriores.',
            'Puntos de carga en cocheras de edificios, coordinando con la administración y el consorcio.',
            'Preparación de la instalación para cargadores monofásicos o trifásicos según lo que tengas disponible.',
        ],
        'secciones' => [
            ['h2' => 'Cargador wallbox o tomacorriente: qué conviene', 'p' => ['Cargar con el cable de emergencia en un tomacorriente común es lento y, en instalaciones que no están preparadas, recalienta cables y conexiones. Un cargador wallbox o un tomacorriente de carga reforzado con circuito propio permite cargar más rápido, con la protección correcta y sin afectar el resto de la casa.', 'La potencia del cargador depende de lo que tenés disponible: en la mayoría de las viviendas monofásicas se instalan cargadores de hasta 7 kW; con suministro trifásico se puede ir a potencias mayores. Te decimos qué opción es realista con tu instalación actual y qué haría falta para ampliarla.']],
            ['h2' => 'Cargador en cochera de edificio', 'p' => ['En apartamentos el punto de carga suele alimentarse desde el medidor de tu unidad hasta la cochera, con un recorrido que atraviesa espacios comunes. Relevamos el trayecto, proponemos la canalización y preparamos la información técnica que la administración o el consorcio suelen pedir para autorizar la obra.', 'Si el edificio quiere instalar varios puntos de carga, planteamos una solución con reparto de carga para que no se sobrecargue la acometida común.']],
            ['h2' => 'Qué revisamos antes de instalar', 'p' => ['Potencia contratada y estado del tablero, sección de los cables existentes, puesta a tierra y distancia entre el tablero y el lugar donde va a estacionar el vehículo. Con eso armamos el presupuesto, que puede incluir la ampliación del tablero o la gestión de un aumento de potencia si tu suministro actual no alcanza.']],
            ['h2' => 'Marcas y compatibilidad', 'p' => ['Instalamos cargadores de las marcas habituales del mercado y los que vienen con el vehículo. Si todavía no compraste el cargador, te orientamos sobre el tipo de conector, la potencia y las funciones que conviene tener, como control de carga por app o programación horaria para cargar de noche.']],
        ],
        'faq' => [
            ['q' => '¿Cuánto tarda la instalación de un cargador para auto eléctrico?', 'a' => 'Depende de la distancia entre el tablero y el punto de carga y del estado de la instalación. Lo definimos al relevar tu caso y te lo indicamos en el presupuesto.'],
            ['q' => '¿Puedo instalar un cargador en la cochera de mi edificio?', 'a' => 'En general sí. Relevamos el recorrido desde tu medidor hasta la cochera y preparamos la información para la administración o el consorcio.'],
            ['q' => '¿Necesito aumentar la potencia contratada para cargar el auto?', 'a' => 'No siempre. Revisamos tu suministro y el consumo de la casa. Si hace falta, te orientamos sobre el trámite y adaptamos la instalación.'],
            ['q' => '¿Sirve para híbridos enchufables?', 'a' => 'Sí. Los híbridos enchufables usan el mismo tipo de punto de carga, generalmente con potencias menores.'],
            ['q' => '¿Instalan cargadores para flotas o comercios?', 'a' => 'Sí. Consultanos por puntos de carga para estacionamientos de empresas, comercios y hoteles.'],
        ],
        'wsp' => 'Hola, quiero instalar un cargador para vehículo eléctrico en Montevideo.',
    ],
];

require __DIR__ . '/servicios_preguntas.php';
foreach ($servicios_landing as $id => $l) {
    $pages[$l['slug']] = ['title' => $l['title'], 'description' => $l['description'], 'heading' => $l['h1'], 'crumb' => $l['crumb'], 'servicio' => $id, 'mod' => $l['mod'] ?? null];
}
require_once __DIR__ . '/barrios.php';
$pages['zonas'] = ['title' => 'Zonas de atención – Electricista en Montevideo y Canelones', 'description' => 'Electricista a domicilio en Montevideo, Ciudad de la Costa, la Costa de Oro y el resto de Canelones. Mirá si llegamos a tu barrio y pedí presupuesto.', 'mod' => '2026-09-25', 'heading' => 'Electricista en Montevideo y Canelones', 'crumb' => 'Zonas de atención', 'zonas' => true];
